import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen">
        <SessionProvider>
          <header className="p-5 bg-blue-950 text-blue-300">
            <div className="flex items-center justify-between">
              <h1>My App</h1>
              <nav className="flex gap-5">
                <Link href="/">Home</Link>
                <Link href="/auth/dashboard">Dashboard</Link>
              </nav>
            </div>
          </header>
          <main className="p-5">{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
}
